AllCops:
  TargetRubyVersion: 3.0.0
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - 'vendor/bundle/**/*'
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

require:
  - rubocop-rails
  - rubocop-performance

Bundler/OrderedGems:
  Enabled: false

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Layout/LineLength:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Layout/ParameterAlignment:
#   EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - Guardfile
  IgnoredMethods:
    - refine
    - class_methods
    - namespace
    - task

Metrics/CyclomaticComplexity:
  Max: 10 # default: 7

Metrics/MethodLength:
  Max: 30 # default: 10

Performance/CaseWhenSplat:
  Enabled: true

Performance/ChainArrayAllocation:
  Enabled: true

Performance/OpenStruct:
  Enabled: true

Rails/FilePath:
  Enabled: false # EnforcedStyle: 'arguments' Forces single-quote to be used, which then triggers the "use double quotes" cop.
  # EnforcedStyle: 'arguments'

# Rails/SkipsModelValidations:
#   Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: literal

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma

Style/WordArray:
  EnforcedStyle: brackets
