version: '2'

services:
  postgres:
    image: 'postgres:13.2'
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis
    ports:
      - '6379:6379'
