version: '2'

services:
  postgres:
    image: 'postgres:13.2' # <--> .github/workflows/tests.yml
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - ./tmp/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
