default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: 127.0.0.1
  port: 54312
  username: <%= ENV.fetch("PG_USER", "postgres") %>

development:
  <<: *default
  database: finances_development

test:
  <<: *default
  database: finances_test
