@startuml Model

hide empty methods
hide circle

package Organisation {
  ' Model created.
  class Book {
    * name
    * default_currency_iso_code: string{3}
  }
  Book "* owner" --* User

  ' Model created.
  class User {
    * email
    * display_name
    * password_digest
  }

  ' Enum created.
  enum BookRoleType < PG Enum > {
    admin
    writer
    reader
  }

  ' Model created.
  class BookRole {
  }
  BookRole --* User
  BookRole --* Book
  BookRole "role" --* BookRoleType
}

package "Register" {
  enum RegisterType < PG Enum > {
    Bank
    Card
    Investment
    Asset
    Liability
    Loan
    Institution
    Expense
    Income
  }

  ' Model created
  class Register {
    * name
    * starts_at
    * currency_iso_code: string{3}
    * initial_balance: integer = 0
    * active: boolean = true
    info: JSON
    notes: text
  }
  Register --* Book
  Register "parent" --o Register
  Register "default category" --o Register
  Register "* type" --* RegisterType

  package Categories {
    ' TODO: Create Rails model
    class Expense < STI > {}
    Expense --|> Register

    ' TODO: Create Rails model
    class Income < STI > {}
    Income --|> Register
  }

  package Accounts {
    ' Model create
    class Asset < STI > {}
    Asset --|> Register

    ' Model created
    class Bank < STI > {}
    Bank --|> Register

    ' Model created
    class BankInfo < Store > {
      account_number: String
      iban: String
    }
    BankInfo o-- Bank

    ' Model created
    class Card < STI > {}
    Card --|> Register

    ' TODO: Create Rails model
    class CardInfo < Store > {
      account_number: String
      iban: String
      interest_rate: Float
      credit_limit: Integer
      card_number: String
      expires_at: DateTime
    }
    CardInfo o-- Card

    ' TODO: Create Rails model
    class Investment < STI > {}
    Investment --|> Register

    ' TODO: Create Rails model
    class InvestmentInfo < Store > {
      account_number: String
    }
    InvestmentInfo o-- Investment

    ' TODO: Create Rails model
    class Liability < STI > {}
    Liability --|> Register

    ' TODO: Create Rails model
    class Loan < STI > {}
    Loan --|> Register

    ' TODO: Create Rails model
    class Other < STI > {}
    Other --|> Register

    ' TODO: Create Rails model
    class Person < STI > {}
    Person --|> Register

    ' TODO: Create Rails model
    class PersonInfo < Store > {
      name: String
      iban: String
    }
    PersonInfo o-- Person
  }
}

package Transaction {
    ' TODO: Create PSQL enum
  enum TransactionStatus < PG Enum > {
    Uncleared
    Reconciling
    Cleared
  }

  ' TODO: Create Rails model
  class Transaction {
    * date: DateTime
    cheque: String
    * description
    memo
  }
  Transaction "* origin" --|> Register

  ' TODO: Create Rails model
  class Split {
    * amount: Integer
    * counterpart_amount: Integer
    memo
  }
  Transaction "1..n" --* Split
  Split "* destination" --* Register
  Split "* status" --* TransactionStatus
}

package Reminders {
  ' TODO: Create PSQL enum
  enum ReminderNature < PG Enum > {
    Reminder
    AutoCommit
    AutoCancel
  }

  ' TODO: Create Rails model
  class Reminder {
    * title
    description
    * from: DateTime
    until: DateTime
    recurrence: String < Montrose >
    transaction_description

  }
  Reminder "* nature" *-- ReminderNature
  Reminder "* origin" --* Register

  ' TODO: Create Rails model
  class ReminderSplit {
    * amount: Integer
    memo
  }
  Reminder "1..n" --* ReminderSplit
  ReminderSplit "* destination" --* Register
  ReminderSplit "* status" --* TransactionStatus
}

package "Applicable to all elements" {
  ' TODO: Create Rails model
  class Tag {
    * name
  }

  ' TODO: Create Rails model
  class Tagging {
    * subject_type
    * subject_id
  }
  Tagging --* Tag

' TODO: Create Rails model
  class ImportOrigin {
    * subject_id
    * subject_type
    * external_system
    * external_id
  }
}

@enduml
