name: Tests

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2 # <--> docker-compose.yml
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: finances
        ports:
          - 5432:5432
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4 # <--> Gemfile
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Get Yarn Cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Node Modules Cache
        id: node-modules-cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Setup Database
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1/finances
          RAILS_ENV: test
        run: bundle exec rails db:setup db:migrate
      - name: Model Annotation
        # To fix: bundle exec rake annotate_models
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1/finances
          ANNOTATE_FROZEN: true
        run: bundle exec rake annotate_models
      - name: Controllers Annotation
        # To fix: bundle exec chusaku
        run: bundle exec chusaku --dry-run --exit-with-error-on-annotation
      - name: Lint
        run: bundle exec rubocop
      - name: Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@127.0.0.1/finances
        run: bundle exec rails test
